# Generated by Django 4.1.3 on 2022-12-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('cena', models.FloatField()),
                ('desc', models.TextField()),
                ('kategoria', models.CharField(choices=[('PIZ', 'Pizza'), ('ONI', 'Onion rings'), ('WIN', 'Chicken wings'), ('BUR', 'Burger'), ('KEB', 'Kebab'), ('SUS', 'Sushi')], max_length=3)),
                ('prod_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
