# Generated by Django 4.1.2 on 2022-12-11 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kategoria',
            field=models.CharField(choices=[('PIZ', 'Pizza'), ('ONI', 'Onion rings'), ('BUR', 'Burger'), ('KEB', 'Kebab'), ('WIN', 'Chicken wings'), ('SUS', 'Sushi')], max_length=3),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255)),
                ('miasto', models.CharField(max_length=255)),
                ('ulica', models.CharField(max_length=255)),
                ('numer_domu_mieszkania', models.IntegerField(max_length=3)),
                ('telefon', models.IntegerField(default=0)),
                ('kodPocztowy', models.IntegerField()),
                ('wojewodztwo', models.CharField(choices=[('wielkopolskie', 'wielkopolskie'), ('dolnośląskie', 'dolnośląskie'), ('zachodniopomorskie', 'zachodniopomorskie'), ('podlaskie', 'podlaskie'), ('małopolskie', 'małopolskie'), ('opolskie', 'opolskie'), ('łódzkie', 'łódzkie'), ('lubuskie', 'lubuskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('pomorskie', 'pomorskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('lubelskie', 'lubelskie'), ('świętokrzyskie', 'świętokrzyskie'), ('śląskie', 'śląskie')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
