# Generated by Django 4.1.2 on 2022-12-12 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_product_kategoria_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='wojewodztwo',
            field=models.CharField(choices=[('świętokrzyskie', 'świętokrzyskie'), ('małopolskie', 'małopolskie'), ('lubelskie', 'lubelskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('podlaskie', 'podlaskie'), ('śląskie', 'śląskie'), ('łódzkie', 'łódzkie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie'), ('lubuskie', 'lubuskie'), ('pomorskie', 'pomorskie'), ('dolnośląskie', 'dolnośląskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('opolskie', 'opolskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='kategoria',
            field=models.CharField(choices=[('BUR', 'Burger'), ('KEB', 'Kebab'), ('WIN', 'Chicken wings'), ('SUS', 'Sushi'), ('PIZ', 'Pizza'), ('ONI', 'Onion rings')], max_length=3),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
