# Generated by Django 4.1.2 on 2022-12-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_client_wojewodztwo_alter_product_kategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='wojewodztwo',
            field=models.CharField(choices=[('małopolskie', 'małopolskie'), ('dolnośląskie', 'dolnośląskie'), ('lubelskie', 'lubelskie'), ('łódzkie', 'łódzkie'), ('świętokrzyskie', 'świętokrzyskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('zachodniopomorskie', 'zachodniopomorskie'), ('śląskie', 'śląskie'), ('opolskie', 'opolskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('pomorskie', 'pomorskie'), ('podlaskie', 'podlaskie'), ('wielkopolskie', 'wielkopolskie'), ('lubuskie', 'lubuskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='kategoria',
            field=models.CharField(choices=[('ONI', 'Onion rings'), ('KEB', 'Kebab'), ('BUR', 'Burger'), ('SUS', 'Sushi'), ('PIZ', 'Pizza'), ('WIN', 'Chicken wings')], max_length=3),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.FloatField()),
                ('orderId', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentId', models.CharField(blank=True, max_length=100, null=True)),
                ('oplacone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataZamowienia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('W oczekiwaniu', 'W oczekiwaniu'), ('Anulowane', 'Anulowane'), ('Spakowane', 'Spakowane'), ('Zaakceptowane', 'Zaakceptowane'), ('Dostarczone', 'Dostarczone'), ('W drodze', 'W drodze')], default='w oczekiwaniu', max_length=255)),
                ('ilosc', models.PositiveBigIntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('platnosc', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
