# Generated by Django 4.1.2 on 2022-12-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_client_wojewodztwo_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='wojewodztwo',
            field=models.CharField(choices=[('zachodniopomorskie', 'zachodniopomorskie'), ('pomorskie', 'pomorskie'), ('małopolskie', 'małopolskie'), ('dolnośląskie', 'dolnośląskie'), ('lubuskie', 'lubuskie'), ('lubelskie', 'lubelskie'), ('wielkopolskie', 'wielkopolskie'), ('podlaskie', 'podlaskie'), ('łódzkie', 'łódzkie'), ('opolskie', 'opolskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('świętokrzyskie', 'świętokrzyskie'), ('śląskie', 'śląskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Packed', 'Packed')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='kategoria',
            field=models.CharField(choices=[('ONI', 'Onion rings'), ('SUS', 'Sushi'), ('WIN', 'Chicken wings'), ('KEB', 'Kebab'), ('BUR', 'Burger'), ('PIZ', 'Pizza')], max_length=3),
        ),
    ]
